spring:
  application:
    name: GMALL-MANAGE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: GMALL-MANAGE
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 3000000
server:
  port: 8081